[tool.poetry]
name = "supportbot"
version = "0.1.0"
description = ""
authors = ["malik"]
readme = "README.md"
packages = [{include = "project"}]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
